config/routes.rb
CheckInLite::Application.routes.draw do

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "check_in/:location_id" => "locations#check_in", :as => "check_in"
delete "delete_location/:location_id" => "locations#destroy", :as => "delete_location"
post "create_location" => "locations#create", :as => "create_location"

#resources :users

get "sessions/new"

#resources :users
resources :sessions
#resources :locatons

resources :users do
	resources :locations
end

root :to => 'users#index'
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :name, :address, :contact_info, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessible :name, :email, :password, :password_confirmation
	attr_accessor :password
	before_save :encrypt_password

	validates_uniqueness_of :email
	validates_presence_of :email, :name
	validates_presence_of :password, :on => :create
	validates_confirmation_of :password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
    else
        nil
    end
  end
    
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
	end
	
	has_many :locations, :order => "updated_at DESC", :limit => 3, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :user_valid

  private

  def login_required
    if session[:user_id]
      return true
    end
    flash[:warning]='Please login to continue'
    session[:return_to]=request.request_uri
    redirect_to(log_in_url)
    return false 
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
    def user_valid?
    if params[:user_id].blank?
      @user = User.find(params[:id])
    else
      @user = User.find(params[:user_id])
    end
    @current_user_from_session = User.find(session[:user_id]) if session[:user_id]
    if session[:user_id] == @user.id
      return true
    elsif @current_user_from_session && @current_user_from_session.email == "mike@mikeshea.net"
      @admin = 1
      return true
    else
      redirect_to(:root, :notice => 'You do not have permission for that page.')
    end
  end
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :user_valid?, :only => ['create', 'destroy']

	def create
	  @user = User.find(params[:user_id])
	  @location = @user.locations.create(params[:location])
    if @location.save
	    respond_to do |format|
	      format.html { redirect_to(@user, :notice => 'Location added.') }
	    end
    else
	    respond_to do |format|
        format.html { redirect_to(@user, :notice => 'Location not added.') }
      end
    end
	end

	def check_in
	  @user = User.find(session[:user_id])
		@location = Location.find(params[:location_id])
		if @user.id == @location.user_id
	    @location.update_attributes(:updated_at => Time.now)
      respond_to do |format|
        format.html { redirect_to(@user, :notice => 'Updated your location.') }
      end
    else
      redirect_to(:root, :notice => 'You do not have permission for that page.')
    end
  end

	def destroy
	  @location = Location.find(params[:id])
    @location.destroy
    respond_to do |format|
      format.html { redirect_to(@user, :notice => 'Location deleted.') }
    end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def create		
		@user = User.authenticate(params[:email], params[:password])
		if @user
			session[:user_id] = @user.id
			redirect_to root_url, :notice => "Account created."
		else
			flash.now.alert = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :only=>['index']
  before_filter :user_valid?, :only => ['show', 'edit', 'update', 'destroy']
  
  def index
    @users = User.all
    #@users = User.find(:all, :joins => "left outer join locations on locations.user_id = users.id", :order => "locations.updated_at DESC")
    @users = User.find(:all, :include => :locations, :order => 'locations.updated_at DESC')
    @user = User.find(session[:user_id])
    
    respond_to do |format|
      format.html
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create  
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user]) && user_valid
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    if !@admin
	    session[:user_id] = nil
	    @user = User.find(session[:user_id])
	  end
    respond_to do |format|
      format.html { redirect_to(root_url) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkin</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= yield :javascript_includes %>
  <%= csrf_meta_tag %>
  </head>
  <body bgcolor="#aaaaaa" onload="initialize()"> 
	<div class="container">
	<h1>Check in</h1>
 
<%= yield %>
 </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form_location.html.erb
<h2>Add a Location:</h2><%= form_for([@user, @user.locations.build]) do |f| %>  <div class="field">    <%= f.label :name %><br />    <%= f.text_field :name %>  </div>  <div class="field">    <%= f.label :address %><br />    <%= f.text_field :address %>  </div>  <div class="field">    <%= f.label "Preferred Contact Method" %><br />    <%= f.text_field :contact_info %>  </div>  <div class="actions">    <%= f.submit %>  </div><% end %>

app/views/users/_location.html.erb
<h2><%= location.name %> (<%= link_to "check in", check_in_path(location.id) %>)</h2><p><strong>Address: </strong><a href="http://www.google.com/maps?q=<%=location.address%>"><%= location.address %></a></p><p><strong>Preferred Contact Method: </strong><%= location.contact_info %></a></p><p><strong>Last Checked In: </strong><%= location.updated_at.strftime('%l:%M %p %Z, %d %b %Y') %></a></p><p><%= link_to 'Destroy', [location.user, location],               :confirm => 'Delete Location?',               :method => :delete %></p><hr>

app/views/users/_location_full.html.erb
<p><h2 class="button"><%= link_to user.location.name, edit_user_location_path(location) %></h2></p> <p><b>Address:</b> <%= location.address %></p><p><b>Preferred Contact:</b> <%= location.contact_info %></p><p><b>Last Checked In:</b> <%= location.updated_at %></p><p><%= link_to 'Destroy', [location.user, location],               :confirm => 'Are you sure?',               :method => :delete %></p><hr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p>Signed in as <%= @user.email %>. <%= link_to "Sign out", log_out_path %>.</p>

<p id="notice"><%= notice %></p>

<table cellpadding="5">
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Preferred Contact Method</th>
	<th>Check In Time</th>
	
  </tr>

<% @users.each do |user| %>
  <tr>
    <td>
	<%= if user.id == session[:user_id] 
		link_to user.name, user
	else 
		user.name
	end
	%>
	<%=
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	if @current_user.email == "mike@mikeshea.net"
		link_to 'Destroy', user, :confirm => 'Are you sure you want to delete your entire user record and all locations?', :method => :delete
	end
	%></td>
	<% if user.locations.exists? %>
	<td><a href="http://www.google.com/maps?q=<%=user.locations.first.address%>"><%= user.locations.first.name %></a></td>
	<td><%= user.locations.first.contact_info %></td>
	<td><%= user.locations.first.updated_at.strftime('%l:%M %p, %d %b %Y') %></td>
    <% else %>
	<td></td>
	<td></td>
	<td></td>
	<% end %>
	
  </tr>

<% end %>
</table>

app/views/users/new.html.erb
<p>Use the following form to sign up for CheckIn. Already signed up? <%= link_to "Log in", log_in_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<p><a href="/">All Users</a></p>
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @user.name %> | 
  <b>Email:</b>
  <%= @user.email %>
| <%= link_to 'Edit', edit_user_path(@user) %> - <%= link_to 'Destroy', @user, :confirm => 'Are you sure you want to delete your entire user record and all locations?', :method => :delete %>
</p>

<%= render :partial => "location",
           :collection => @user.locations %>

<%= render 'form_location' %>